import { COMMON_ACTIONS } from "../static/constant"

const initialState ={
     companyInfo:{
        "userInfo": {
          "userId": 195,
          "relationshipId": 129,
          "formId": 156,
          "locationId": 0,
          "subscriptionId": 6,
          "email": "charu.ralli@alpide.com",
          "jobRoleName": null,
          "password": "Charu@123",
          "newPassword": null,
          "toRevoke": false,
          "homeCountry": null,
          "source": null,
          "notifyUser": 0,
          "status": "Active",
          "statusColor": " success",
          "lastLoginDate": null,
          "dateCreated": "2024-03-19 06:04:32",
          "dateUpdated": null,
          "createdByUserId": 0,
          "updatedByUserId": 0,
          "userType": "non_admin",
          "isFromEmailVerified": 0,
          "isAccountHolder": "1",
          "salutation": null,
          "firstName": "Charu",
          "middleName": null,
          "lastName": "Ralli",
          "workPhone": null,
          "cellPhone": null,
          "faxNumber": null,
          "relationshipEmployeeId": 270,
          "isB2CCustomer": 0,
          "customerId": 0,
          "boUserPermissionList": [
            {
              "userPermissionId": 183,
              "version": 20,
              "secondoryPermissionJson": null,
              "permissionJson": null,
              "clientUserAccountId": 195,
              "relationshipId": 129,
              "dateCreated": "2024-03-19 06:05:40",
              "createdByUserId": 0,
              "dateUpdated": null,
              "updatedByUserId": 0,
              "boUserPrimaryPermission": [
                {
                  "userPrimaryPermissionId": 24322,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "A",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24323,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "B",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24324,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "C",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24325,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "D",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24327,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "F",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24328,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "G",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24329,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "H",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24330,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "I",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24331,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "J",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24332,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "K",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24333,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "L",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24334,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "M",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24335,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "N",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24336,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "O",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24337,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "P",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24338,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "Q",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24339,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "R",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24340,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "S",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24341,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "T",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24342,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "U",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24343,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "V",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24344,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "W",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24345,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "X",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24346,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "Y",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24347,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "Z",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24348,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AA",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24349,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AB",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24350,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AC",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24352,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AE",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24353,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AF",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24354,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AG",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24355,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AH",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24356,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AI",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24362,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AO",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24365,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AR",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24366,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AS",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24368,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AU",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24369,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AV",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24371,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AX",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24373,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AZ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24374,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BA",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24375,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BB",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24376,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BC",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24377,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BD",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24378,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BE",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24381,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BH",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24383,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BJ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24384,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BK",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24385,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BL",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24386,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BM",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24387,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BN",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24390,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BQ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24391,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BR",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24392,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BS",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24393,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BT",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24394,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BU",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24396,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BW",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24398,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BY",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24399,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BZ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24401,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CB",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24408,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CI",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24410,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CK",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24412,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CM",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24413,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CN",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24414,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CO",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24415,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CP",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24416,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CQ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24417,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CR",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24418,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CS",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24419,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CT",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24420,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CU",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24421,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CV",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24422,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CW",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24423,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CX",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24425,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CZ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24426,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DA",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24427,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DB",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24428,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DC",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24429,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DD",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24430,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DE",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24435,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DJ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24436,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DK",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24437,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DL",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24438,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DM",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24441,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DP",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24442,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DQ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24443,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DR",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24445,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DT",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24448,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DW",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24449,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DX",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24450,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DY",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24451,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DZ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24452,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EA",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24453,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EB",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24454,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EC",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24455,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "ED",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24456,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EE",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24457,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EF",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24458,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EG",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24459,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EH",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24460,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EI",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24461,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EJ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24462,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EK",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24463,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EL",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24464,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EM",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24465,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EN",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24466,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EO",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24474,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EW",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24475,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EX",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24476,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EY",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24477,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EZ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24478,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FA",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24479,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FB",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24480,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FC",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24482,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FE",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24483,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FF",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24485,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FH",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 24486,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FI",
                  "permisssionValue": 15,
                  "dateCreated": "2024-09-28 11:03:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 25883,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "MQ",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-09 09:46:20",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26074,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "EP",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-09 12:56:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26075,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "AK",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-09 12:56:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26077,
                  "relationshipId": 129,
                  "version": 1,
                  "moduleCode": "CF",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-09 12:56:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26078,
                  "relationshipId": 129,
                  "version": 1,
                  "moduleCode": "CG",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-09 12:56:55",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26651,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "ER",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26652,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "ES",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26653,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FM",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26654,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FP",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26655,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FQ",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26656,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FR",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26657,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FS",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26658,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "CD",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26659,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FK",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26660,
                  "relationshipId": 129,
                  "version": 1,
                  "moduleCode": "FW",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26661,
                  "relationshipId": 129,
                  "version": 1,
                  "moduleCode": "FJ",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26662,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DV",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26663,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FU",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26664,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FT",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26665,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FV",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 10:23:40",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26666,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "FO",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 11:20:07",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26668,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "BI",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-10 11:37:14",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26818,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DS",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-22 10:23:45",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26819,
                  "relationshipId": 129,
                  "version": 0,
                  "moduleCode": "DF",
                  "permisssionValue": 0,
                  "dateCreated": "2024-10-22 10:23:45",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                },
                {
                  "userPrimaryPermissionId": 26820,
                  "relationshipId": 129,
                  "version": 1,
                  "moduleCode": "BP",
                  "permisssionValue": 15,
                  "dateCreated": "2024-10-22 10:23:45",
                  "isDelete": null,
                  "isCreate": null,
                  "isUpdate": null,
                  "isRead": null
                }
              ],
              "alpideUserPlanPermission": []
            }
          ],
          "ssoAccountId": 117,
          "token": null
        },
        "defaultCompany": {
          "relationshipId": 129,
          "version": 4,
          "email": null,
          "onlineStorePaymentGatewayId": 0,
          "defaultPaymentGatewayId": 0,
          "defaultPaymentGatewayName": null,
          "accountActivationToken": "6efbc3aa-f042-41d1-99e3-6915cc2f0332-24.03.19.06.04.32",
          "storeName": "Tanak Jewels",
          "onlineThemes": "\"{}\"",
          "logoAwsObjectKey": "129-f3f3358b-dfca-4f1b-984e-d5485f8125a2-2024.03.19.06.08.42",
          "isUpdateInventoryOnSalesInvoice": 0,
          "isUpdateInventoryOnPurchaseInvoice": 0,
          "currencyCode": "INR",
          "currencyIcon": "fa fa-rupee",
          "countryName": "India",
          "countryId": 45,
          "ebayRefreshToken": null,
          "isEbayPermission": 0,
          "fyStartDate": "2024-04-01 11:38:15",
          "fyEndDate": "2025-03-31 11:38:26",
          "gstNumber": null,
          "panNumber": null,
          "vatNumber": null,
          "phoneNumber": "9910156756",
          "timezone": "GMT+05:30) IST Asia/Kolkata",
          "faxNumber": null,
          "website": null,
          "decimalDigitsLengthQty": 0,
          "decimalDigitsLengthPrice": 2,
          "isActive": 0,
          "industryId": 1809,
          "isToShowFlag": 0,
          "isSubscriptionValid": null,
          "isCompanySetupRequired": 0,
          "howDidYouHear": null,
          "accoutingtype": null,
          "financialyear": null,
          "companySize": "1-9",
          "avgMonthlySOorInvoices": null,
          "approxInventoryItems": null,
          "accountingType": "Accrual",
          "hasAccountActivated": 1,
          "dateCreated": "2024-03-19 06:04:32",
          "accountActivationDate": "2024-03-19 06:05:41",
          "dateUpdated": null,
          "createdByUserId": 0,
          "updatedByUserId": 0,
          "paymentTermId": 840,
          "isFreeTrial": 0,
          "freeDays": 30,
          "planModule": "A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z,AA,AB,AC,AD,AE,AF,AG,AH,AI,AJ,AK,AL,AM,AN,AO,AP,AQ,AR,AS,AT,AU,AV,AW,AX,AY,AZ,BA,BB,BC,BD,BE,BF,BG,BH,BI,BJ,BK,BL,BM,BN,BO,BP,BQ,BR,BS,BT,BU,BV,BW,MQ,BX,BY,BZ,CA,CB,CC,CD,CE,CF,CG,CH,CI,CJ,CK,CL,CM,CN,CO,CP,CQ,CR,CS,CT,CU,CV,CW,CX,CY,CZ,DA,DB,DC,DD,DE,DF,DG,DG",
          "alpideProductId": 0,
          "planId": 4,
          "planCode": "27",
          "countryCallingCode": 91,
          "labelConfig": "",
          "roundingOffSettings": "{\"isRoundingOffTotalAmtOnSalesInvoice\":1,\"roundingOffSalesLedgerAccountId\":339}",
          "bucketName": "alpide-prod-129",
          "isStopSalesInvoiceForOutOfStock": 0,
          "costCenter": null,
          "messageForUI": null,
          "isDesktop": null,
          "boLocationList": [
            {
              "locationId": 1773,
              "locationName": null,
              "cityName": "Noida",
              "streetAddress1": "C-116, Sector 2",
              "streetAddress2": "",
              "stateName": "Uttar Pradesh",
              "customerId": 0,
              "supplierId": 0,
              "crmTargetId": 0,
              "crmLeadId": 0,
              "zipCode": "201301",
              "countryId": 45,
              "warehouseMasterId": 0,
              "employeeId": 0,
              "countryName": "India",
              "relationshipId": 129,
              "isDefault": 0,
              "additionalValues": null,
              "dateCreated": "2024-03-19 07:28:16",
              "dateUpdated": null,
              "createdBy": null,
              "updatedBy": null,
              "locationType": "RelationshipBillingAddress",
              "boContactId": 0,
              "boContactUI": null,
              "gstStateCode": 0,
              "dateCreatedForUI": 1710833296000,
              "dateUpdatedForUI": null
            },
            {
              "locationId": 1774,
              "locationName": null,
              "cityName": "Noida",
              "streetAddress1": "D-220, Sector 2",
              "streetAddress2": "",
              "stateName": "Uttar Pradesh",
              "customerId": 0,
              "supplierId": 0,
              "crmTargetId": 0,
              "crmLeadId": 0,
              "zipCode": "201301",
              "countryId": 45,
              "warehouseMasterId": 0,
              "employeeId": 0,
              "countryName": "India",
              "relationshipId": 129,
              "isDefault": 1,
              "additionalValues": null,
              "dateCreated": "2024-03-19 07:29:32",
              "dateUpdated": null,
              "createdBy": null,
              "updatedBy": null,
              "locationType": "RelationshipBillingAddress",
              "boContactId": 0,
              "boContactUI": null,
              "gstStateCode": 0,
              "dateCreatedForUI": 1710833372000,
              "dateUpdatedForUI": null
            },
            {
              "locationId": 1915,
              "locationName": null,
              "cityName": "Khora",
              "streetAddress1": "123, Market Main Road",
              "streetAddress2": "Naya Bazar",
              "stateName": "Uttar Pradesh",
              "customerId": 0,
              "supplierId": 0,
              "crmTargetId": 0,
              "crmLeadId": 0,
              "zipCode": "201307",
              "countryId": 45,
              "warehouseMasterId": 0,
              "employeeId": 0,
              "countryName": "India",
              "relationshipId": 129,
              "isDefault": 1,
              "additionalValues": null,
              "dateCreated": "2024-04-29 10:15:06",
              "dateUpdated": null,
              "createdBy": null,
              "updatedBy": null,
              "locationType": "RelationshipShippingAddress",
              "boContactId": 0,
              "boContactUI": null,
              "gstStateCode": 0,
              "dateCreatedForUI": 1714385706000,
              "dateUpdatedForUI": null
            }
          ],
          "costCenterList": [],
          "defaultCoaLedgerAccountsList": [
            {
              "clientDefaultCoaLedgerAccountId": 2787,
              "version": 0,
              "txType": "Sales",
              "ledgerAccountId": 82,
              "ledgerAccountGroupId": 30,
              "coaCategoryId": 6,
              "coaCategoryGroupId": 4,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2788,
              "version": 0,
              "txType": "Purchases",
              "ledgerAccountId": 49,
              "ledgerAccountGroupId": 23,
              "coaCategoryId": 8,
              "coaCategoryGroupId": 3,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2789,
              "version": 0,
              "txType": "Debtors",
              "ledgerAccountId": 20,
              "ledgerAccountGroupId": 8,
              "coaCategoryId": 5,
              "coaCategoryGroupId": 1,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2790,
              "version": 0,
              "txType": "Creditors",
              "ledgerAccountId": 42,
              "ledgerAccountGroupId": 20,
              "coaCategoryId": 3,
              "coaCategoryGroupId": 2,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2791,
              "version": 0,
              "txType": "Sales Discount",
              "ledgerAccountId": 73,
              "ledgerAccountGroupId": 28,
              "coaCategoryId": 13,
              "coaCategoryGroupId": 3,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2792,
              "version": 0,
              "txType": "Discount Received",
              "ledgerAccountId": 85,
              "ledgerAccountGroupId": 31,
              "coaCategoryId": 7,
              "coaCategoryGroupId": 4,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2793,
              "version": 0,
              "txType": "Sales Output Tax",
              "ledgerAccountId": 92,
              "ledgerAccountGroupId": 21,
              "coaCategoryId": 3,
              "coaCategoryGroupId": 2,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2794,
              "version": 0,
              "txType": "Purchase Input Tax",
              "ledgerAccountId": 93,
              "ledgerAccountGroupId": 11,
              "coaCategoryId": 5,
              "coaCategoryGroupId": 1,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2795,
              "version": 0,
              "txType": "Credit Memo",
              "ledgerAccountId": 83,
              "ledgerAccountGroupId": 30,
              "coaCategoryId": 6,
              "coaCategoryGroupId": 4,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2796,
              "version": 0,
              "txType": "Debit Memo",
              "ledgerAccountId": 50,
              "ledgerAccountGroupId": 23,
              "coaCategoryId": 8,
              "coaCategoryGroupId": 3,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2797,
              "version": 0,
              "txType": "Customer Expense",
              "ledgerAccountId": 97,
              "ledgerAccountGroupId": 31,
              "coaCategoryId": 7,
              "coaCategoryGroupId": 4,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2798,
              "version": 0,
              "txType": "Supplier Expense",
              "ledgerAccountId": 98,
              "ledgerAccountGroupId": 28,
              "coaCategoryId": 13,
              "coaCategoryGroupId": 3,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2799,
              "version": 0,
              "txType": "Payment Recieved",
              "ledgerAccountId": 20,
              "ledgerAccountGroupId": 8,
              "coaCategoryId": 5,
              "coaCategoryGroupId": 1,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            },
            {
              "clientDefaultCoaLedgerAccountId": 2800,
              "version": 0,
              "txType": "Cash in hand",
              "ledgerAccountId": 22,
              "ledgerAccountGroupId": 9,
              "coaCategoryId": 5,
              "coaCategoryGroupId": 1,
              "relationshipId": 129,
              "dateCreated": null,
              "dateUpdated": null,
              "createdByUserId": 0,
              "updatedByUserId": 0
            }
          ],
          "bankDetails": [
            {
              "bankDetailId": 44,
              "version": 0,
              "relationshipId": 129,
              "name": "SBI",
              "accountNumber": "37050006099985",
              "ifscCode": "SBI097664",
              "dateCreated": null
            },
            {
              "bankDetailId": 49,
              "version": 4,
              "relationshipId": 129,
              "name": "HDFC",
              "accountNumber": "45363636364363",
              "ifscCode": "HDFC0958",
              "dateCreated": null
            },
            {
              "bankDetailId": 52,
              "version": 6,
              "relationshipId": 129,
              "name": "ICICI",
              "accountNumber": "42425325235",
              "ifscCode": "ICICI745547",
              "dateCreated": null
            },
            {
              "bankDetailId": 53,
              "version": 2,
              "relationshipId": 129,
              "name": "PNB",
              "accountNumber": "67456845745745",
              "ifscCode": "PUNB5252",
              "dateCreated": null
            }
          ],
          "relationshipEmployees": {
            "relationshipEmployeeId": 270,
            "version": 0,
            "relationshipId": 129,
            "firstName": "Charu",
            "middleName": null,
            "lastName": "Ralli",
            "emailAddress": "charu.ralli@alpide.com",
            "cellNumber": null,
            "dob": null,
            "gender": null,
            "religion": null,
            "maritalStatus": null,
            "emergencyContactName": null,
            "emergencyContactNumber": null,
            "fileName": null,
            "bucketName": null,
            "folderName": null,
            "locationList": [],
            "employeeCode": null,
            "dateOfJoining": null,
            "departmentId": 0,
            "departmentName": null,
            "teamId": 0,
            "teamName": null,
            "designationId": 0,
            "designationName": null,
            "hierarchyId": 108,
            "hierarchyName": "CEO",
            "hierarchyLevel": "1",
            "hierarchyCode": "AAAA.....Z",
            "managerId": 0,
            "managerName": null,
            "jobRoleId": 0,
            "jobRoleName": null,
            "empTypeId": 0,
            "empType": null,
            "jobTitleId": 0,
            "jobTitleName": null,
            "isAccountHolder": 1,
            "hasSoftwareAccess": 1,
            "workPhone": null,
            "salutationName": null,
            "preferCallName": null,
            "faxNumber": null,
            "cellPhone": null,
            "logoAwsObjectKey": null,
            "faceId": null,
            "imageUrl": null,
            "dateCreated": "2024-03-19 06:04:32",
            "instructorClassRefList": [],
            "relationshipEmpJobRoleRefList": [],
            "fullName": "Charu Ralli"
          },
          "relationshipEmployeesList": [],
          "customerGstinDetailsEntity": [],
          "industryName": "ERP",
          "couponSetting": "{\"isCoupanAppliedBeforeTax\":1}",
          "currentTermEnd": null,
          "nextBillingAt": null,
          "clientUserAccountId": 0
        }
      }
}


export const commonReducer =(state=initialState , action)=>{


    switch(action.type){

        case COMMON_ACTIONS.LOGGEDIN_INFO:
            return {...state , companyInfo: action.data}

            default:
                return state;
    }
}